// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTagToSession(arg1, arg2) {
  return window['go']['main']['App']['AddTagToSession'](arg1, arg2);
}

export function DeleteAppCategory(arg1) {
  return window['go']['main']['App']['DeleteAppCategory'](arg1);
}

export function DeleteHierarchicalSummary(arg1) {
  return window['go']['main']['App']['DeleteHierarchicalSummary'](arg1);
}

export function DeleteModel(arg1) {
  return window['go']['main']['App']['DeleteModel'](arg1);
}

export function DeleteScreenshot(arg1) {
  return window['go']['main']['App']['DeleteScreenshot'](arg1);
}

export function DeleteSession(arg1) {
  return window['go']['main']['App']['DeleteSession'](arg1);
}

export function DeleteTag(arg1) {
  return window['go']['main']['App']['DeleteTag'](arg1);
}

export function DeleteTimelineCategoryRule(arg1) {
  return window['go']['main']['App']['DeleteTimelineCategoryRule'](arg1);
}

export function DiscoverGitRepositories(arg1, arg2) {
  return window['go']['main']['App']['DiscoverGitRepositories'](arg1, arg2);
}

export function DownloadModel(arg1) {
  return window['go']['main']['App']['DownloadModel'](arg1);
}

export function DownloadServer() {
  return window['go']['main']['App']['DownloadServer']();
}

export function ExportAnalytics(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExportAnalytics'](arg1, arg2, arg3);
}

export function ExportReport(arg1, arg2) {
  return window['go']['main']['App']['ExportReport'](arg1, arg2);
}

export function ForceCapture() {
  return window['go']['main']['App']['ForceCapture']();
}

export function GenerateReport(arg1, arg2, arg3) {
  return window['go']['main']['App']['GenerateReport'](arg1, arg2, arg3);
}

export function GenerateSummary(arg1) {
  return window['go']['main']['App']['GenerateSummary'](arg1);
}

export function GetActivityTags(arg1) {
  return window['go']['main']['App']['GetActivityTags'](arg1);
}

export function GetAllApps() {
  return window['go']['main']['App']['GetAllApps']();
}

export function GetAllTags() {
  return window['go']['main']['App']['GetAllTags']();
}

export function GetAppCategories() {
  return window['go']['main']['App']['GetAppCategories']();
}

export function GetAppUsage(arg1, arg2) {
  return window['go']['main']['App']['GetAppUsage'](arg1, arg2);
}

export function GetAvailableModels() {
  return window['go']['main']['App']['GetAvailableModels']();
}

export function GetAvailableMonitors() {
  return window['go']['main']['App']['GetAvailableMonitors']();
}

export function GetBundledStatus() {
  return window['go']['main']['App']['GetBundledStatus']();
}

export function GetCalendarHeatmap(arg1, arg2) {
  return window['go']['main']['App']['GetCalendarHeatmap'](arg1, arg2);
}

export function GetCategorizationRules() {
  return window['go']['main']['App']['GetCategorizationRules']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetCurrentTime() {
  return window['go']['main']['App']['GetCurrentTime']();
}

export function GetCustomRangeStats(arg1, arg2) {
  return window['go']['main']['App']['GetCustomRangeStats'](arg1, arg2);
}

export function GetDaemonStatus() {
  return window['go']['main']['App']['GetDaemonStatus']();
}

export function GetDailyStats(arg1) {
  return window['go']['main']['App']['GetDailyStats'](arg1);
}

export function GetDailySummaries(arg1) {
  return window['go']['main']['App']['GetDailySummaries'](arg1);
}

export function GetDataDir() {
  return window['go']['main']['App']['GetDataDir']();
}

export function GetDataSourceStats(arg1, arg2) {
  return window['go']['main']['App']['GetDataSourceStats'](arg1, arg2);
}

export function GetFileAllowedExtensions() {
  return window['go']['main']['App']['GetFileAllowedExtensions']();
}

export function GetFocusDistribution(arg1) {
  return window['go']['main']['App']['GetFocusDistribution'](arg1);
}

export function GetHierarchicalSummary(arg1, arg2) {
  return window['go']['main']['App']['GetHierarchicalSummary'](arg1, arg2);
}

export function GetHourlyActivity(arg1) {
  return window['go']['main']['App']['GetHourlyActivity'](arg1);
}

export function GetHourlyActivityHeatmap() {
  return window['go']['main']['App']['GetHourlyActivityHeatmap']();
}

export function GetInferenceSetupStatus() {
  return window['go']['main']['App']['GetInferenceSetupStatus']();
}

export function GetInferenceStatus() {
  return window['go']['main']['App']['GetInferenceStatus']();
}

export function GetLatestHierarchicalSummaries() {
  return window['go']['main']['App']['GetLatestHierarchicalSummaries']();
}

export function GetMonthlyStats(arg1, arg2) {
  return window['go']['main']['App']['GetMonthlyStats'](arg1, arg2);
}

export function GetProductivityScore(arg1) {
  return window['go']['main']['App']['GetProductivityScore'](arg1);
}

export function GetRecentSessions(arg1) {
  return window['go']['main']['App']['GetRecentSessions'](arg1);
}

export function GetReport(arg1) {
  return window['go']['main']['App']['GetReport'](arg1);
}

export function GetReportHistory() {
  return window['go']['main']['App']['GetReportHistory']();
}

export function GetScreenshot(arg1) {
  return window['go']['main']['App']['GetScreenshot'](arg1);
}

export function GetScreenshotInfo(arg1) {
  return window['go']['main']['App']['GetScreenshotInfo'](arg1);
}

export function GetScreenshotPath(arg1) {
  return window['go']['main']['App']['GetScreenshotPath'](arg1);
}

export function GetScreenshotsForDate(arg1) {
  return window['go']['main']['App']['GetScreenshotsForDate'](arg1);
}

export function GetScreenshotsForHour(arg1, arg2) {
  return window['go']['main']['App']['GetScreenshotsForHour'](arg1, arg2);
}

export function GetScreenshotsForSession(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetScreenshotsForSession'](arg1, arg2, arg3);
}

export function GetServerStatus() {
  return window['go']['main']['App']['GetServerStatus']();
}

export function GetSessionContext(arg1) {
  return window['go']['main']['App']['GetSessionContext'](arg1);
}

export function GetSessionsForDate(arg1) {
  return window['go']['main']['App']['GetSessionsForDate'](arg1);
}

export function GetStorageStats() {
  return window['go']['main']['App']['GetStorageStats']();
}

export function GetSummary(arg1) {
  return window['go']['main']['App']['GetSummary'](arg1);
}

export function GetSummaryBySession(arg1) {
  return window['go']['main']['App']['GetSummaryBySession'](arg1);
}

export function GetSystemInfo() {
  return window['go']['main']['App']['GetSystemInfo']();
}

export function GetSystemTheme() {
  return window['go']['main']['App']['GetSystemTheme']();
}

export function GetThumbnailPath(arg1) {
  return window['go']['main']['App']['GetThumbnailPath'](arg1);
}

export function GetTimelineGridData(arg1) {
  return window['go']['main']['App']['GetTimelineGridData'](arg1);
}

export function GetTopWindows(arg1, arg2) {
  return window['go']['main']['App']['GetTopWindows'](arg1, arg2);
}

export function GetTrackedRepositories() {
  return window['go']['main']['App']['GetTrackedRepositories']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function GetWatchedDirectories() {
  return window['go']['main']['App']['GetWatchedDirectories']();
}

export function GetWeeklyStats(arg1) {
  return window['go']['main']['App']['GetWeeklyStats'](arg1);
}

export function GetYearlyStats(arg1) {
  return window['go']['main']['App']['GetYearlyStats'](arg1);
}

export function IsReady() {
  return window['go']['main']['App']['IsReady']();
}

export function ListHierarchicalSummaries(arg1, arg2) {
  return window['go']['main']['App']['ListHierarchicalSummaries'](arg1, arg2);
}

export function MergeTags(arg1, arg2) {
  return window['go']['main']['App']['MergeTags'](arg1, arg2);
}

export function OpenDataDir() {
  return window['go']['main']['App']['OpenDataDir']();
}

export function OptimizeDatabase() {
  return window['go']['main']['App']['OptimizeDatabase']();
}

export function ParseTimeRange(arg1) {
  return window['go']['main']['App']['ParseTimeRange'](arg1);
}

export function PauseCapture() {
  return window['go']['main']['App']['PauseCapture']();
}

export function RegenerateSummary(arg1) {
  return window['go']['main']['App']['RegenerateSummary'](arg1);
}

export function RegisterGitRepository(arg1) {
  return window['go']['main']['App']['RegisterGitRepository'](arg1);
}

export function RemoveTagFromSession(arg1, arg2) {
  return window['go']['main']['App']['RemoveTagFromSession'](arg1, arg2);
}

export function RenameTag(arg1, arg2) {
  return window['go']['main']['App']['RenameTag'](arg1, arg2);
}

export function RestartTracking() {
  return window['go']['main']['App']['RestartTracking']();
}

export function ResumeCapture() {
  return window['go']['main']['App']['ResumeCapture']();
}

export function SaveAppCategory(arg1, arg2) {
  return window['go']['main']['App']['SaveAppCategory'](arg1, arg2);
}

export function SetAppTimelineCategory(arg1, arg2) {
  return window['go']['main']['App']['SetAppTimelineCategory'](arg1, arg2);
}

export function SetFileAllowedExtensions(arg1) {
  return window['go']['main']['App']['SetFileAllowedExtensions'](arg1);
}

export function SetTagsForSession(arg1, arg2) {
  return window['go']['main']['App']['SetTagsForSession'](arg1, arg2);
}

export function StartTracking() {
  return window['go']['main']['App']['StartTracking']();
}

export function StopTracking() {
  return window['go']['main']['App']['StopTracking']();
}

export function UnregisterGitRepository(arg1) {
  return window['go']['main']['App']['UnregisterGitRepository'](arg1);
}

export function UnwatchDirectory(arg1) {
  return window['go']['main']['App']['UnwatchDirectory'](arg1);
}

export function UpdateConfig(arg1) {
  return window['go']['main']['App']['UpdateConfig'](arg1);
}

export function UpdateHierarchicalSummary(arg1, arg2) {
  return window['go']['main']['App']['UpdateHierarchicalSummary'](arg1, arg2);
}

export function WatchDirectory(arg1) {
  return window['go']['main']['App']['WatchDirectory'](arg1);
}
