// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteScreenshot(arg1) {
  return window['go']['main']['App']['DeleteScreenshot'](arg1);
}

export function ExportReport(arg1, arg2) {
  return window['go']['main']['App']['ExportReport'](arg1, arg2);
}

export function ForceCapture() {
  return window['go']['main']['App']['ForceCapture']();
}

export function GenerateReport(arg1, arg2) {
  return window['go']['main']['App']['GenerateReport'](arg1, arg2);
}

export function GetAppUsage(arg1, arg2) {
  return window['go']['main']['App']['GetAppUsage'](arg1, arg2);
}

export function GetCalendarHeatmap(arg1, arg2) {
  return window['go']['main']['App']['GetCalendarHeatmap'](arg1, arg2);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetCurrentTime() {
  return window['go']['main']['App']['GetCurrentTime']();
}

export function GetDaemonStatus() {
  return window['go']['main']['App']['GetDaemonStatus']();
}

export function GetDailyStats(arg1) {
  return window['go']['main']['App']['GetDailyStats'](arg1);
}

export function GetDataDir() {
  return window['go']['main']['App']['GetDataDir']();
}

export function GetDataSourceStats(arg1, arg2) {
  return window['go']['main']['App']['GetDataSourceStats'](arg1, arg2);
}

export function GetHourlyActivity(arg1) {
  return window['go']['main']['App']['GetHourlyActivity'](arg1);
}

export function GetRecentSessions(arg1) {
  return window['go']['main']['App']['GetRecentSessions'](arg1);
}

export function GetReport(arg1) {
  return window['go']['main']['App']['GetReport'](arg1);
}

export function GetReportHistory() {
  return window['go']['main']['App']['GetReportHistory']();
}

export function GetScreenshot(arg1) {
  return window['go']['main']['App']['GetScreenshot'](arg1);
}

export function GetScreenshotInfo(arg1) {
  return window['go']['main']['App']['GetScreenshotInfo'](arg1);
}

export function GetScreenshotPath(arg1) {
  return window['go']['main']['App']['GetScreenshotPath'](arg1);
}

export function GetScreenshotsForHour(arg1, arg2) {
  return window['go']['main']['App']['GetScreenshotsForHour'](arg1, arg2);
}

export function GetScreenshotsForSession(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetScreenshotsForSession'](arg1, arg2, arg3);
}

export function GetSessionContext(arg1) {
  return window['go']['main']['App']['GetSessionContext'](arg1);
}

export function GetSessionsForDate(arg1) {
  return window['go']['main']['App']['GetSessionsForDate'](arg1);
}

export function GetStorageStats() {
  return window['go']['main']['App']['GetStorageStats']();
}

export function GetSystemInfo() {
  return window['go']['main']['App']['GetSystemInfo']();
}

export function GetThumbnailPath(arg1) {
  return window['go']['main']['App']['GetThumbnailPath'](arg1);
}

export function GetTrackedRepositories() {
  return window['go']['main']['App']['GetTrackedRepositories']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function GetWatchedDirectories() {
  return window['go']['main']['App']['GetWatchedDirectories']();
}

export function GetWeeklyStats(arg1) {
  return window['go']['main']['App']['GetWeeklyStats'](arg1);
}

export function OpenDataDir() {
  return window['go']['main']['App']['OpenDataDir']();
}

export function ParseTimeRange(arg1) {
  return window['go']['main']['App']['ParseTimeRange'](arg1);
}

export function RegisterGitRepository(arg1) {
  return window['go']['main']['App']['RegisterGitRepository'](arg1);
}

export function RestartTracking() {
  return window['go']['main']['App']['RestartTracking']();
}

export function StartTracking() {
  return window['go']['main']['App']['StartTracking']();
}

export function StopTracking() {
  return window['go']['main']['App']['StopTracking']();
}

export function UnregisterGitRepository(arg1) {
  return window['go']['main']['App']['UnregisterGitRepository'](arg1);
}

export function UnwatchDirectory(arg1) {
  return window['go']['main']['App']['UnwatchDirectory'](arg1);
}

export function UpdateConfig(arg1) {
  return window['go']['main']['App']['UpdateConfig'](arg1);
}

export function WatchDirectory(arg1) {
  return window['go']['main']['App']['WatchDirectory'](arg1);
}
