// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {storage} from '../models';
import {service} from '../models';
import {main} from '../models';
import {inference} from '../models';
import {tracker} from '../models';

export function DeleteAppCategory(arg1:string):Promise<void>;

export function DeleteModel(arg1:string):Promise<void>;

export function DeleteScreenshot(arg1:number):Promise<void>;

export function DeleteSession(arg1:number):Promise<void>;

export function DiscoverGitRepositories(arg1:Array<string>,arg2:number):Promise<Array<storage.GitRepository>>;

export function DownloadModel(arg1:string):Promise<void>;

export function DownloadServer():Promise<void>;

export function ExportAnalytics(arg1:string,arg2:string,arg3:string):Promise<string>;

export function ExportReport(arg1:number,arg2:string):Promise<string>;

export function ForceCapture():Promise<string>;

export function GenerateReport(arg1:string,arg2:string,arg3:boolean):Promise<storage.Report>;

export function GenerateSummary(arg1:number):Promise<storage.Summary>;

export function GetActivityTags(arg1:string):Promise<Array<service.TagUsage>>;

export function GetAllApps():Promise<Array<main.AppWithCategory>>;

export function GetAppCategories():Promise<Array<storage.AppCategoryRecord>>;

export function GetAppUsage(arg1:number,arg2:number):Promise<Array<service.AppUsage>>;

export function GetAvailableModels():Promise<Array<inference.ModelInfo>>;

export function GetAvailableMonitors():Promise<Array<tracker.MonitorInfo>>;

export function GetBundledStatus():Promise<inference.BundledStatus>;

export function GetCalendarHeatmap(arg1:number,arg2:number):Promise<service.CalendarData>;

export function GetConfig():Promise<service.Config>;

export function GetCurrentTime():Promise<number>;

export function GetCustomRangeStats(arg1:string,arg2:string):Promise<service.CustomRangeStats>;

export function GetDaemonStatus():Promise<service.DaemonStatus>;

export function GetDailyStats(arg1:string):Promise<service.DailyStats>;

export function GetDailySummaries(arg1:number):Promise<Array<service.DailySummary>>;

export function GetDataDir():Promise<string>;

export function GetDataSourceStats(arg1:number,arg2:number):Promise<service.DataSourceStats>;

export function GetFileAllowedExtensions():Promise<Array<string>>;

export function GetFocusDistribution(arg1:string):Promise<Array<service.HourlyFocus>>;

export function GetHourlyActivity(arg1:string):Promise<Array<service.HourlyActivity>>;

export function GetHourlyActivityHeatmap():Promise<Array<service.HeatmapData>>;

export function GetInferenceSetupStatus():Promise<inference.SetupStatus>;

export function GetInferenceStatus():Promise<inference.InferenceStatus>;

export function GetMonthlyStats(arg1:number,arg2:number):Promise<service.MonthlyStats>;

export function GetProductivityScore(arg1:string):Promise<service.ProductivityScore>;

export function GetRecentSessions(arg1:number):Promise<Array<storage.Session>>;

export function GetReport(arg1:number):Promise<storage.Report>;

export function GetReportHistory():Promise<Array<service.ReportMeta>>;

export function GetScreenshot(arg1:number):Promise<storage.Screenshot>;

export function GetScreenshotInfo(arg1:number):Promise<service.ScreenshotInfo>;

export function GetScreenshotPath(arg1:number):Promise<string>;

export function GetScreenshotsForDate(arg1:string):Promise<Array<storage.Screenshot>>;

export function GetScreenshotsForHour(arg1:string,arg2:number):Promise<Array<storage.Screenshot>>;

export function GetScreenshotsForSession(arg1:number,arg2:number,arg3:number):Promise<service.ScreenshotPage>;

export function GetServerStatus():Promise<inference.ServerDownloadStatus>;

export function GetSessionContext(arg1:number):Promise<service.SessionContext>;

export function GetSessionsForDate(arg1:string):Promise<Array<service.SessionSummary>>;

export function GetStorageStats():Promise<service.StorageStats>;

export function GetSummary(arg1:number):Promise<storage.Summary>;

export function GetSummaryBySession(arg1:number):Promise<storage.Summary>;

export function GetSystemInfo():Promise<Record<string, string>>;

export function GetSystemTheme():Promise<string>;

export function GetThumbnailPath(arg1:number):Promise<string>;

export function GetTopWindows(arg1:string,arg2:number):Promise<Array<service.WindowUsage>>;

export function GetTrackedRepositories():Promise<Array<storage.GitRepository>>;

export function GetVersion():Promise<string>;

export function GetWatchedDirectories():Promise<Array<string>>;

export function GetWeeklyStats(arg1:string):Promise<service.WeeklyStats>;

export function GetYearlyStats(arg1:number):Promise<service.YearlyStats>;

export function IsReady():Promise<boolean>;

export function OpenDataDir():Promise<void>;

export function OptimizeDatabase():Promise<number>;

export function ParseTimeRange(arg1:string):Promise<service.TimeRange>;

export function PauseCapture():Promise<void>;

export function RegenerateSummary(arg1:number):Promise<storage.Summary>;

export function RegisterGitRepository(arg1:string):Promise<storage.GitRepository>;

export function RestartTracking():Promise<void>;

export function ResumeCapture():Promise<void>;

export function SaveAppCategory(arg1:string,arg2:string):Promise<void>;

export function SetFileAllowedExtensions(arg1:Array<string>):Promise<void>;

export function StartTracking():Promise<void>;

export function StopTracking():Promise<void>;

export function UnregisterGitRepository(arg1:number):Promise<void>;

export function UnwatchDirectory(arg1:string):Promise<void>;

export function UpdateConfig(arg1:Record<string, any>):Promise<void>;

export function WatchDirectory(arg1:string):Promise<void>;
